</$objtype/mkfile

LIB=libhubbub.$O.a
OBJ=\
	charset/detect.$O \
	parser.$O \
	tokeniser/entities.$O \
	tokeniser/tokeniser.$O \
	treebuilder/after_after_body.$O \
	treebuilder/after_after_frameset.$O \
	treebuilder/after_body.$O \
	treebuilder/after_frameset.$O \
	treebuilder/after_head.$O \
	treebuilder/before_head.$O \
	treebuilder/before_html.$O \
	treebuilder/generic_rcdata.$O \
	treebuilder/in_body.$O \
	treebuilder/in_caption.$O \
	treebuilder/in_cell.$O \
	treebuilder/in_column_group.$O \
	treebuilder/in_foreign_content.$O \
	treebuilder/in_frameset.$O \
	treebuilder/in_head.$O \
	treebuilder/in_head_noscript.$O \
	treebuilder/in_row.$O \
	treebuilder/in_select.$O \
	treebuilder/in_select_in_table.$O \
	treebuilder/in_table.$O \
	treebuilder/in_table_body.$O \
	treebuilder/initial.$O \
	treebuilder/treebuilder.$O \
	utils/errors.$O \
	utils/string.$O

#HFILES=../include/parserutils/parserutils.h

<../../nsport.mk

HFILES=\
	../include/hubbub/errors.h \
	../include/hubbub/functypes.h \
	../include/hubbub/hubbub.h \
	../include/hubbub/parser.h \
	../include/hubbub/tree.h \
	../include/hubbub/types.h \

CFLAGS=$CFLAGS -I../../libparserutils/include

<../../nsportlib.mk


tokeniser/entities.inc:
	cp ../../genfiles/libhubbub/entities.inc tokeniser/entities.inc
